version: '3.4'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./client:/usr/src/app/client
      - ./Intl:/usr/src/app/Intl
      - ./server:/usr/src/app/server
      - ./.babelrc:/usr/src/app/.babelrc
      - ./index.js:/usr/src/app/index.js
      - ./nodemon.json:/usr/src/app/nodemon.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./webpack.config.babel.js:/usr/src/app/webpack.config.babel.js
      - ./webpack.config.dev.js:/usr/src/app/webpack.config.dev.js
      - ./webpack.config.prod.js:/usr/src/app/webpack.config.prod.js
      - ./webpack.config.server.js:/usr/src/app/webpack.config.server.js
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://db:27017/mern-starter
    stdin_open: true
    tty: true
  db:
    image: mongo:latest
    volumes:
      - dbdata:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
volumes:
  dbdata:
  esdata1:
    driver: local
  esdata2:
    driver: local

networks:
  esnet: